//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lowes.Catalog.Importer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lowes_catalogEntities : DbContext
    {
        public lowes_catalogEntities()
            : base("name=lowes_catalogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<collection> collections { get; set; }
        public DbSet<collections_groups> collections_groups { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<roomtype> roomtypes { get; set; }
        public DbSet<spatialcategory> spatialcategories { get; set; }
    }
}
