//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lowes.Catalog.Importer
{
    using System;
    using System.Collections.Generic;
    
    public partial class collections_groups
    {
        public int collectionId { get; set; }
        public int groupId { get; set; }
        public bool isDefault { get; set; }
    
        public virtual collection collection { get; set; }
        public virtual group group { get; set; }
    }
}
