//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lowes.Catalog.Importer
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public group()
        {
            this.collections_groups = new HashSet<collections_groups>();
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public string marketingBullets { get; set; }
        public string imageUrl { get; set; }
        public string color { get; set; }
        public string material { get; set; }
        public string size { get; set; }
        public string Finish { get; set; }
        public string roomType { get; set; }
        public string category { get; set; }
        public string spatialCategory { get; set; }
        public bool isEnabled { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
        public string unit { get; set; }
    
        public virtual category category1 { get; set; }
        public virtual ICollection<collections_groups> collections_groups { get; set; }
        public virtual roomtype roomtype1 { get; set; }
        public virtual spatialcategory spatialcategory1 { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
